# Generated by Django 5.1.7 on 2025-03-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('closed', 'Closed'), ('upcoming', 'Open Soon')], default='upcoming', max_length=10),
        ),
    ]
